FROM openjdk:8-jre-alpine
USER root
COPY . /app
WORKDIR /app
RUN chmod 777 * -R
RUN ls -l
RUN PWD
RUN ./runApp.sh test
RUN ls -l

EXPOSE 8080
ENV SPRING_PROFILES_ACTIVE local
CMD ["java", "-jar", "SpringMvcJpaSample-0.0.1-SNAPSHOT.jar"]

